using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class fps : MonoBehaviour
{
    public float totalTimeInSeconds = 30f; // 5ï¿½ï¿½ = 300ï¿½b
    public string agentTag = "Agent";
    public string FinishTag = "Finish";
    public string FinishTag2 = "Finish2";

    private float elapsedTime = 0.1f;
    [SerializeField]
    private int FPS = 60;
    public float time = 0f;
    public float interval = 10;
    private int i = 1;
    private bool active = false;
    // Start is called before the first frame update
    void Start()
    {
        Application.targetFrameRate = FPS;
        // 30ï¿½bï¿½ï¿½ï¿½Æ‚ï¿½CheckElapsedTimeï¿½ï¿½ï¿½\ï¿½bï¿½hï¿½ï¿½ï¿½ï¿½ï¿½s
    }

    // Update is called once per frame
    void Update()
    {
        if (active)
        {
            // ï¿½oï¿½ßï¿½ï¿½Ô‚ï¿½ï¿½Xï¿½V
            elapsedTime += Time.deltaTime;
            if (elapsedTime >= interval && i != 10)
            {
                Debug.Log(i * 30 + "ï¿½b");
                // ï¿½^ï¿½Oï¿½ï¿½ï¿½tï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì”zï¿½ï¿½ï¿½ï¿½æ“¾
                GameObject[] agents = GameObject.FindGameObjectsWithTag(agentTag);
                GameObject[] finishs = GameObject.FindGameObjectsWithTag(FinishTag);
                GameObject[] finishs2 = GameObject.FindGameObjectsWithTag(FinishTag2);
                // ï¿½zï¿½ï¿½Ì—vï¿½fï¿½ï¿½ï¿½iï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìï¿½ï¿½jï¿½ï¿½\ï¿½ï¿½
                Debug.Log($"Number of agents with tag '{agentTag}': {agents.Length}");
                Debug.Log($"Number of agents with tag '{FinishTag}': {finishs.Length + finishs2.Length}");
                elapsedTime = 0;
                i++;
            }

            // ï¿½oï¿½ßï¿½ï¿½Ô‚ï¿½ï¿½wï¿½ï¿½Ìï¿½ï¿½Ô‚ğ’´‚ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½
            if (i == 10)
            {
                // ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‹Lï¿½q
                Debug.Log("5ï¿½ï¿½ï¿½oï¿½ß‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½ï¿½Bï¿½Qï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½B");
                // ï¿½^ï¿½Oï¿½ï¿½

                // ï¿½^ï¿½Oï¿½ï¿½ï¿½tï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì”zï¿½ï¿½ï¿½ï¿½æ“¾
                GameObject[] agents = GameObject.FindGameObjectsWithTag(agentTag);
                GameObject[] finishs = GameObject.FindGameObjectsWithTag(FinishTag);

                // ï¿½zï¿½ï¿½Ì—vï¿½fï¿½ï¿½ï¿½iï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìï¿½ï¿½jï¿½ï¿½\ï¿½ï¿½
                Debug.Log($"Number of agents with tag '{agentTag}': {agents.Length}");
                Debug.Log($"Number of agents with tag '{FinishTag}': {finishs.Length}");
                // ï¿½Aï¿½vï¿½ï¿½ï¿½Pï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½
                Time.timeScale = time;
                i++;
            }
        }

    }
    void Ac()
    {
        active = true;
    }
}
