using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Generate : MonoBehaviour
{
    public GameObject Agent;
    public GameObject Agent2;
    public GameObject Finish;
    public GameObject Finish2;
    public GameObject startgameObject;
    [SerializeField] private int Agentnum = 90;
   [SerializeField] private int Finishnum = 60;
    [SerializeField] private int Agentnumber = 0;
    [SerializeField] private int Agentnumber2 = 0;
    [SerializeField] private int Finishnumber = 0;
    [SerializeField] private int Finishnumber2 = 0;
    public float castRadius = 0.3f;
    private bool obstacleHit = true;
    private int x = 0; //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Åƒï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ÈˆÊ’uï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½Ü‚ÅŠJï¿½nï¿½ï¿½ï¿½È‚ï¿½(fps.cs)
    // Start is called before the first frame update
    public bool R = false;
    void Start()
    {
        a(Agentnum);
        b(Finishnum);
        
        seisei(Agent, Agentnumber);
        seisei(Agent2, Agentnumber2);
        seisei(Finish, Finishnumber);
        seisei(Finish2, Finishnumber2);
        Time.timeScale = 0;
    }


    // Update is called once per frame
    void Update()
    {
        if (R)
        {
            //Debug.Log(x);
            Time.timeScale = 0.3f; // ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½Ô‚ï¿½1/10ï¿½É‚ï¿½ï¿½ï¿½
            startgameObject.gameObject.SendMessage("Ac",  SendMessageOptions.DontRequireReceiver);
        }
    }
Vector3 GetRandomPosition()
{
    // ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ÈˆÊ’uï¿½ğ¶ï¿½ï¿½ï¿½ï¿½Ä•Ô‚ï¿½ï¿½ï¿½ï¿½\ï¿½bï¿½h
    float randomX = Random.Range(-19.5f, 19.5f);
    float randomY = Random.Range(39.5f, -39.5f);
    return new Vector3(randomX, randomY, 0f);
    }

    void seisei(GameObject obj,int generatenumber)
    {
        for (int i = 0; i < generatenumber; i++)
        {
            obstacleHit = true;
            while (obstacleHit)
            {
                GameObject newObject = Instantiate(obj, GetRandomPosition(), Quaternion.identity);

                // ï¿½ï¿½ï¿½aï¿½ï¿½ï¿½Ì‚ï¿½ï¿½×‚Ä‚ï¿½Collider2Dï¿½ï¿½ï¿½ï¿½ï¿½o
                Collider2D[] colliders = Physics2D.OverlapCircleAll(newObject.transform.position, castRadius);

                obstacleHit = false;

                // ï¿½eCollider2Dï¿½É‘Î‚ï¿½ï¿½Äï¿½ï¿½ï¿½
                foreach (Collider2D collider in colliders)
                {
                    // ï¿½^ï¿½Oï¿½ï¿½ï¿½wï¿½è‚µï¿½ï¿½ï¿½ï¿½Qï¿½ï¿½ï¿½Ìƒ^ï¿½Oï¿½Æˆï¿½vï¿½ï¿½ï¿½é‚©ï¿½mï¿½F
                    if (collider.CompareTag("obstacle")&&collider.CompareTag("Confluence"))
                    {
                        obstacleHit = true;
                        Destroy(newObject);  // ï¿½ï¿½Qï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Îï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½jï¿½ï¿½
                        break;  // ï¿½ï¿½Qï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Â‚Å‚ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ê‚½ï¿½çƒ‹ï¿½[ï¿½vï¿½ğ”²‚ï¿½ï¿½ï¿½
                    }
                }
            }
        }
    }
    void a(int num)
    {
        int j = 0;
        for(int i = 0; i < num; i++)
        {
            j = Random.Range(1, 11);
                if(j <= 7)
            {
                Agentnumber++;
            }
            else
            {
                Agentnumber2++;
            }
        }
    }
    void b(int num)
    {
        int j = 0;
        for (int i = 0; i < num; i++)
        {
            j = Random.Range(1, 11);
                if (j <= 7)
            {
                Finishnumber++;
            }
            else
            {
                Finishnumber2++;
            }
        }
    }
    /*void xplus()
    {
        x++;
    }*/
}
