using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class golehantei : MonoBehaviour
{
    public float viewRadius = 10f;        // è¦–é‡ã®åŠå¾„
    public float viewAngle = 40f;        // è¦–é‡ã®è§’åº¦(å·¦å³ã«ã¯ãã‚Œãã‚ŒviewAngle/2)
    public GameObject kyuujo;
    public bool isTouched = false;//ï¿½Ô‚Â‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½
    // Start is called before the first frame update
    private LayerMask ignoreLayer;
    void Start()
    {
        ignoreLayer = 4 << gameObject.layer;
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    /// <summary>
    ///ï¿½@ï¿½ï¿½ï¿½ï¿½ipolygon)ï¿½É“ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½Gï¿½[ï¿½Wï¿½Fï¿½ï¿½ï¿½g(tag==Finish)ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½
    /// </summary>
    /// <param name="other"></param>
    void OnTriggerStay2D(Collider2D other)
    {
        /*RaycastHit hit;
        Ray ray = new Ray()*/
        Vector2 direction = other.gameObject.transform.position - this.transform.position;
        float distance = direction.magnitude;

        // Raycastï¿½ğ”­Ë‚ï¿½ï¿½ÄÕ“Ë‚ï¿½ï¿½ï¿½ï¿½o
        RaycastHit2D hit = Physics2D.Raycast(this.transform.position, direction, 10f, ignoreLayer);

        if (hit.collider != null)
        {
            Debug.Log("ï¿½ï¿½Qï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½: " + hit.collider.name);
            // ï¿½ï¿½ï¿½ï¿½ï¿½Éï¿½Qï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ê‚½ï¿½ê‡ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½Ç‰ï¿½
        }


        if (other.gameObject.tag == "Player")
        {
            DetectCollidersInFieldOfView(other.gameObject);
            
        }

    }   
    //ç¯„å›²ï¼ˆviewAngleåº¦)ã®ä¸­ã«ã‚ã‚‹ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã ã‘æ¤œçŸ¥
    void DetectCollidersInFieldOfView(GameObject otherObject)
    {
        Collider2D[] colliders = Physics2D.OverlapCircleAll(transform.position, viewRadius);

        foreach (Collider2D collider in colliders)
        {
            Vector2 dirToCollider = (collider.transform.position - transform.position).normalized;
            float angleToCollider = Vector2.Angle(transform.up, dirToCollider);

            // è¦–é‡è§’åº¦å†…ã®Colliderã ã‘ã‚’æ¤œçŸ¥
            if (angleToCollider < viewAngle * 0.5f&&collider.name == otherObject.gameObject.name)
            {
                transform.parent.GetComponent<NavMeshAgent2D>().hantei(otherObject);
                isTouched = false;
            }
        }
    }
}
