using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class hantei : MonoBehaviour
{
    public float viewRadius = 100f; //è¦–é‡åŠå¾„(ç¾åœ¨ã‚¤ãƒ³ã‚¹ãƒšã‚¯ã‚¿ãƒ¼ã§å¤‰æ›´ã§ãã‚‹)
    public float viewAngle = 60f;// è¦–é‡ã®è§’åº¦(å·¦å³ã«ã¯ãã‚Œãã‚ŒviewAngle/2)
    public bool isTouched = false;//ï¿½Ô‚Â‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½
    // Start is called before the first frame update
    private LayerMask ignoreLayer;
    private bool nottuiju = true;
    
    
    void Start()
    {
        ignoreLayer = 4 << gameObject.layer;
    }

    // Update is called once per frame
    void Update()
    {
        Debug.Log(nottuiju);
        nottuiju = true;
        
       //DetectVisibleObjects(); //è¦–é‡è§’ã‚’ã‚¹ã‚¯ãƒªãƒ—ãƒˆã§åˆ¶å¾¡
    }
    /// <summary>
    ///ï¿½@ï¿½ï¿½ï¿½ï¿½ipolygon)ï¿½É“ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½Gï¿½[ï¿½Wï¿½Fï¿½ï¿½ï¿½g(tag==Finish)ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½
    /// </summary>
    /// <param name="other"></param>
    void OnTriggerStay2D(Collider2D other)
    {
        /*RaycastHit hit;
        Ray ray = new Ray()*/
        Vector2 direction = other.gameObject.transform.position - this.transform.position;
        float distance = direction.magnitude;

        // Raycastï¿½ğ”­Ë‚ï¿½ï¿½ÄÕ“Ë‚ï¿½ï¿½ï¿½ï¿½o
        RaycastHit2D hit = Physics2D.Raycast(this.transform.position, direction, 10f, ignoreLayer);

        if (hit.collider != null)
        {
            Debug.Log("ï¿½ï¿½Qï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½: " + hit.collider.name);
            // ï¿½ï¿½ï¿½ï¿½ï¿½Éï¿½Qï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ê‚½ï¿½ê‡ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½Ç‰ï¿½
        }


        if (other.gameObject.tag == "Finish")
        {
            bool De = DetectCollidersInFieldOfView(other.gameObject);
            if (De == true)
            {
                bool Ob = ObstacleBetween(transform.position, other.transform.position, other.gameObject);
                if (Ob == false)
                {
                    //gameObject.transform.root.gameObjectã ã¨butaiã‚’æŒã£ã¦ãã¦ã—ã¾ã†
                    other.gameObject.SendMessage("tui", gameObject.transform.parent.gameObject, SendMessageOptions.DontRequireReceiver);
                    if (nottuiju)
                    {
                        transform.parent.GetComponent<yuudoufollow>().hantei(other.gameObject);

                        isTouched = false;
                        }
                    }
                }
            }



        }

        //colliderã®æŒ‡å®šã—ãŸè§’åº¦ã®ä¸­ã«ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆãŒã‚ã‚‹å ´åˆã®ã¿ã®åˆ¤å®šï¼ˆé€”ä¸­ã«éšœå®³ç‰©ãŒãªã„ï¼‰
        // void DetectVisibleObjects()
        //     {
        //         Collider2D[] colliders = Physics2D.OverlapCircleAll(transform.position, viewRadius);

        //         foreach (Collider2D collider in colliders)
        //         {
        //             Vector2 dirToCollider = (collider.transform.position - transform.position).normalized;
        //             float angleToCollider = Vector2.Angle(transform.up, dirToCollider);

        //             // è¦–é‡è§’åº¦å†…ã®Colliderã ã‘ã‚’æ¤œçŸ¥
        //             if (angleToCollider < viewAngle * 0.5f)
        //             {
        //                 ObstacleBetween(transform.position, collider.transform.position, viewRadius,collider.gameObject);

        //             }
        //         }
        //     }

        bool DetectCollidersInFieldOfView(GameObject otherObject)
        {
            Collider2D[] colliders = Physics2D.OverlapCircleAll(transform.position, viewRadius);

            foreach (Collider2D collider in colliders)
            {
                Vector2 customDirection = Quaternion.Euler(0, 0, 270f) * transform.up;
                Vector2 dirToCollider = (collider.transform.position - transform.position).normalized;
                float angleToCollider = Vector2.Angle(customDirection, dirToCollider);
                // è¦–é‡è§’åº¦å†…ã®Colliderã ã‘ã‚’æ¤œçŸ¥
                if (angleToCollider < viewAngle * 0.5f && collider.name == otherObject.gameObject.name)
                {

                    isTouched = false;
                    return true;
                }
            }
            return false;
        }

        //ç¾åœ¨ä½ç½®ã‹ã‚‰æ¤œçŸ¥ã—ãŸã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®é–“ã«éšœå®³ç‰©ãŒã‚ã‚‹ã‹ã©ã†ã‹
        bool ObstacleBetween(Vector2 start, Vector2 target, GameObject otherObject)
        {
            Vector2 rayDirection = otherObject.transform.position - transform.position;
            float rayDistance = rayDirection.magnitude;
            RaycastHit2D[] hits = Physics2D.RaycastAll(transform.position, rayDirection, rayDistance);
            //int i = 1;
            /*LineRenderer lineRenderer = GetComponent<LineRenderer>();
            lineRenderer.positionCount = 2;
            lineRenderer.SetPosition(0,transform.position);
            lineRenderer.SetPosition(1, otherObject.transform.position);*/

            // hitsã‚’ãƒ«ãƒ¼ãƒ—ã—ã¦å‡¦ç†
            foreach (RaycastHit2D hit in hits)//rayã«ã¯OnTriggerStay2Dã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã¯æ¤œçŸ¥ã•ã‚Œãªã„
            {
                //Debug.Log(i);
                //Debug.Log(hit.collider);
                // å½“ãŸã£ãŸColliderãŒæ¤œçŸ¥ã—ãŸã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã§ãªã„å ´åˆ
                if (hit.collider != null) {
                    if (hit.collider.CompareTag("rescue") && !otherObject == transform.root.gameObject || hit.collider.CompareTag("GameController") || hit.collider.CompareTag("Agent") || hit.collider.CompareTag("obstacle")) {
                        return true;
                    }
                }
                //i++;
            }
            return false;
        }
        
    }
