using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class yuudouinhantei : MonoBehaviour
{
    

    public GameObject kyuujo;
    public bool isTouched = false;//ï¿½Ô‚Â‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½
    // Start is called before the first frame update
    private LayerMask ignoreLayer;
    void Start()
    {
        ignoreLayer = 4 << gameObject.layer;
    }

    // Update is called once per frame
    void Update()
    {
       
    }
    /// <summary>
    ///ï¿½@ï¿½ï¿½ï¿½ï¿½ipolygon)ï¿½É“ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½Gï¿½[ï¿½Wï¿½Fï¿½ï¿½ï¿½g(tag==Finish)ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½
    /// </summary>
    /// <param name="other"></param>
    void OnTriggerStay2D(Collider2D other)
    {
        /*RaycastHit hit;
        Ray ray = new Ray()*/
        Vector2 direction = other.gameObject.transform.position - this.transform.position;
        float distance = direction.magnitude;

        // Raycastï¿½ğ”­Ë‚ï¿½ï¿½ÄÕ“Ë‚ï¿½ï¿½ï¿½ï¿½o
        RaycastHit2D hit = Physics2D.Raycast(this.transform.position, direction, 10f, ignoreLayer);

        if (hit.collider != null)
        {
            Debug.Log("ï¿½ï¿½Qï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½: " + hit.collider.name);
            // ï¿½ï¿½ï¿½ï¿½ï¿½Éï¿½Qï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ê‚½ï¿½ê‡ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½Ç‰ï¿½
        }


        if (other.gameObject.tag == "GameController")
        {
            bool Ob = ObstacleBetween(transform.position,other.transform.position,other.gameObject);
            if(Ob == false){
                transform.parent.GetComponent<yuudoufollow>().hantei(other.gameObject);
            
                isTouched = false;
            }
        }

    }

    
    
    bool ObstacleBetween(Vector2 start, Vector2 target,GameObject otherObject)
    {
        Vector2 rayDirection = otherObject.transform.position - transform.position;
        float rayDistance = rayDirection.magnitude;
        RaycastHit2D[] hits = Physics2D.RaycastAll(transform.position, rayDirection, rayDistance );
            //int i = 1;
          // hitsã‚’ãƒ«ãƒ¼ãƒ—ã—ã¦å‡¦ç†
         foreach (RaycastHit2D hit in hits)//rayã«ã¯OnTriggerStay2Dã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã¯æ¤œçŸ¥ã•ã‚Œãªã„
        {
            //Debug.Log(i);
            //Debug.Log(hit.collider);
            // å½“ãŸã£ãŸColliderãŒæ¤œçŸ¥ã—ãŸã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã§ãªã„å ´åˆ
           if(hit.collider != null){
                if(hit.collider.CompareTag("Agent")||hit.collider.CompareTag("obstacle")||!otherObject == transform.root.gameObject){
                    return true;
                }
            }
            //i++;
        }
        return false;
    }
}
